### ISSUE TITLE
Need latest config

### ISSUE THREAD

**Issue by wires** [histograph/config#1]
Missing some fields
- `.data`
- `.data.geonames.countries`, etc..

**Comment by bertspaan** [comment]
My HD crashed last night... I can't do anything right now...
Op 9 jun. 2015 07:12 schreef "Jelle Herold" notifications@github.com:

**Comment by bertspaan** [comment]
I'm able to access my laptop's HD using somebody else's laptop. Added `data` section: https://github.com/histograph/config/commit/67c3555fea826feb6156fcb5e967be64c3565f01

**Comment by wires** [comment]
:feelsgood: hardcore
