### ISSUE TITLE
Using histograph-config in another project with a different schema

### ISSUE THREAD

**Issue by por** [histograph/config#7]
Currently [histograph-config](https://github.com/histograph/config) has a fixed schema. This means it’s not compatible to use with any other project with a different schema. We’re currently experiencing problems with this in [transparantnederland](https://github.com/transparantnederland) projects.

Since a project can have dependencies that also `require(histograph-config)`, like [histograph-stats](https://github.com/histograph/stats) or [histograph-schema](https://github.com/histograph/schema), using `npm link` is not a very robust option because it would mean doing it recursively for any submodule that might require `histograph-config`.

**Comment by por** [comment]
I suggest adding an optional `HISTOGRAPH_CONFIG_DIR` or `--config-dir` flag next to the existing `HISTOGRAPH_CONFIG` or `--config` flag.

This way we could pass a directory containing:

```
/path/to/config
├── config.schema.json
├── default.yml
└── local.yml
```

This approach is similar to the [node-config](https://github.com/lorenwest/node-config) package. They separate the config package from the actual config files. This would mean that `histograph-config` would simply fetch and validate config files according to a given schema. The config files would live in a different directory or repository.

Since this would change the architecture of histograph too much, I propose the `HISTOGRAPH_CONFIG_DIR` as an alternative and simple solution. I took a quick stab at it and the code would look something like this:

``` js
…
var config, data, files, schema, schemaFile, validate;

var configFile = argv.config || process.env.HISTOGRAPH_CONFIG;
var configDir = argv['config-dir'] || process.env.HISTOGRAPH_CONFIG_DIR;

if (configDir) {
  files = [
    path.join(configDir, 'default.yml'),
    path.join(configDir, 'local.yml')
  ];
  schemaFile = path.join(configDir, 'config.schema.json');
} else if (configFile) {
  files = [
    path.join(__dirname, 'histograph.default.yml'),
    configFile
  ];
  schemaFile = path.join(__dirname, 'config.schema.json');
} else {
  die('Please specify location of your user configuration in environment variable `HISTOGRAPH_CONFIG` or `HISTOGRAPH_CONFIG_DIR`, or use the `--config` or `--config-dir` command line option');
}

data = files.map(function(file) {
  try {
    return yaml.safeLoad(fs.readFileSync(file, 'utf8'));
  } catch (err) {
    die(util.format('Can’t open configuration file `%s` due to: \n`%s`', file, err.message));
  }
});

// Merge default config file with user config
// However, arrays should not be merged - all arrays in default config which are
// also in userConfig should be emptied first
config = _.merge(data[0], data[1], function(a, b) {
  if (_.isArray(a)) {
    return b;
  }
});

try {
  schema = fs.readFileSync(schemaFile, 'utf8');
} catch (err) {
  die(util.format('Can’t open schema file `%s` due to: \n`%s`', schemaFile, err.message));
}

validate = validator(schema);

if (validate(config)) {
  return config;
} else {
  die('Invalid configuration file: ' + JSON.stringify(validate.errors));
}
…
```

Any thoughts @bertspaan @tomdemeyer @wires? I don’t have write access to this repository, but if I do I can submit a PR.

**Comment by bertspaan** [comment]
Good plan! Do you want write access, or do you want to do this change with a PR?

**Comment by por** [comment]
@bertspaan I think I need write access for a PR too, unless I fork.

**Comment by bertspaan** [comment]
@por I've invited you to Histograph org. Is that enough, or do I need to set repo-specific rights?

**Comment by por** [comment]
@bertspaan looks like I need some extra access rights:

``` zsh
tim config (feature/dir*) 2h24m » git push
ERROR: Permission to histograph/config.git denied to por.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by bertspaan** [comment]
@por Or maybe we should start using [node-config](https://github.com/lorenwest/node-config) at some point
